
package calculadora_facherita;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Panel;
import java.awt.Toolkit;
import java.io.ObjectInputStream;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;   
import javax.swing.ImageIcon;

/**
 *
 * @author diogenes.celis
 */
public class Calculadora_facherita extends javax.swing.JFrame {

    ScriptEngineManager sem = new ScriptEngineManager();
    ScriptEngine se = sem.getEngineByName("JavaScript");
    
     int x, y;
    
    
    
    
    /*/ScriptEngineManager sem = new ScriptEngineManager();
    ScriptEngine se = sem.getEngineByName("javascript"); /*/
    
    public Calculadora_facherita() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono_calculadora.png")));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        decorade = new javax.swing.JPanel();
        minum = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        decorade1 = new javax.swing.JPanel();
        minum1 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonera = new javax.swing.JPanel();
        btn_c = new javax.swing.JButton();
        btn_ce = new javax.swing.JButton();
        btn_porc = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_00 = new javax.swing.JButton();
        btn_multi = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_mas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pantalla = new javax.swing.JPanel();
        btn_modo = new javax.swing.JButton();
        txtoperacion = new javax.swing.JLabel();
        txtresultado = new javax.swing.JLabel();

        decorade.setBackground(new java.awt.Color(201, 201, 202));
        decorade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        decorade.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                decoradeMouseDragged(evt);
            }
        });
        decorade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                decoradeMousePressed(evt);
            }
        });
        decorade.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minum.setFont(new java.awt.Font("Consolas", 1, 70)); // NOI18N
        minum.setForeground(new java.awt.Color(255, 153, 51));
        minum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minum.setText("•");
        minum.setToolTipText("");
        minum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minumMouseClicked(evt);
            }
        });
        decorade.add(minum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, 20, 30));

        exit.setFont(new java.awt.Font("Consolas", 1, 70)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 51, 51));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("•");
        exit.setToolTipText("");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        decorade.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 20, 30));

        jLabel1.setForeground(new java.awt.Color(85, 90, 96));
        jLabel1.setText("calculadora - @diogenes.celis");
        decorade.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decorade1.setBackground(new java.awt.Color(201, 201, 202));
        decorade1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        decorade1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                decorade1MouseDragged(evt);
            }
        });
        decorade1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                decorade1MousePressed(evt);
            }
        });
        decorade1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minum1.setFont(new java.awt.Font("Consolas", 1, 70)); // NOI18N
        minum1.setForeground(new java.awt.Color(255, 153, 51));
        minum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minum1.setText("•");
        minum1.setToolTipText("");
        minum1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minum1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minum1MouseClicked(evt);
            }
        });
        decorade1.add(minum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, 20, 30));

        exit1.setFont(new java.awt.Font("Consolas", 1, 70)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 51, 51));
        exit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit1.setText("•");
        exit1.setToolTipText("");
        exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });
        decorade1.add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 20, 30));

        jLabel2.setForeground(new java.awt.Color(85, 90, 96));
        jLabel2.setText("calculadora - @diogenes.celis");
        decorade1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 20));

        jPanel1.add(decorade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 20));

        botonera.setBackground(new java.awt.Color(236, 250, 253));

        btn_c.setBackground(new java.awt.Color(204, 204, 204));
        btn_c.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_c.setForeground(new java.awt.Color(42, 123, 179));
        btn_c.setText("C");
        btn_c.setBorder(null);
        btn_c.setContentAreaFilled(false);
        btn_c.setFocusPainted(false);
        btn_c.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_c.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_c.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_c.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cActionPerformed(evt);
            }
        });

        btn_ce.setBackground(new java.awt.Color(204, 204, 204));
        btn_ce.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_ce.setForeground(new java.awt.Color(85, 90, 96));
        btn_ce.setText("CE");
        btn_ce.setBorder(null);
        btn_ce.setContentAreaFilled(false);
        btn_ce.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_ce.setFocusPainted(false);
        btn_ce.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ce.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_ce.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ceActionPerformed(evt);
            }
        });

        btn_porc.setBackground(new java.awt.Color(204, 204, 204));
        btn_porc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_porc.setForeground(new java.awt.Color(85, 90, 96));
        btn_porc.setText("%");
        btn_porc.setBorder(null);
        btn_porc.setContentAreaFilled(false);
        btn_porc.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_porc.setFocusPainted(false);
        btn_porc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_porc.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_porc.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_porc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_porcActionPerformed(evt);
            }
        });

        btn_div.setBackground(new java.awt.Color(204, 204, 204));
        btn_div.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_div.setForeground(new java.awt.Color(42, 123, 179));
        btn_div.setText("/");
        btn_div.setBorder(null);
        btn_div.setContentAreaFilled(false);
        btn_div.setFocusPainted(false);
        btn_div.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_div.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_div.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_div.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });

        btn_7.setBackground(new java.awt.Color(204, 204, 204));
        btn_7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_7.setForeground(new java.awt.Color(85, 90, 96));
        btn_7.setText("7");
        btn_7.setBorder(null);
        btn_7.setContentAreaFilled(false);
        btn_7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_7.setFocusPainted(false);
        btn_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_7.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_7.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_02.png"))); // NOI18N
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setBackground(new java.awt.Color(204, 204, 204));
        btn_8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_8.setForeground(new java.awt.Color(85, 90, 96));
        btn_8.setText("8");
        btn_8.setBorder(null);
        btn_8.setContentAreaFilled(false);
        btn_8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_8.setFocusPainted(false);
        btn_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_8.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_8.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_02.png"))); // NOI18N
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_9.setBackground(new java.awt.Color(204, 204, 204));
        btn_9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_9.setForeground(new java.awt.Color(85, 90, 96));
        btn_9.setText("9");
        btn_9.setBorder(null);
        btn_9.setContentAreaFilled(false);
        btn_9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_9.setFocusPainted(false);
        btn_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_9.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_9.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_02.png"))); // NOI18N
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_4.setBackground(new java.awt.Color(204, 204, 204));
        btn_4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_4.setForeground(new java.awt.Color(85, 90, 96));
        btn_4.setText("4");
        btn_4.setBorder(null);
        btn_4.setContentAreaFilled(false);
        btn_4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_4.setFocusPainted(false);
        btn_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_4.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_4.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_02.png"))); // NOI18N
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setBackground(new java.awt.Color(204, 204, 204));
        btn_5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_5.setForeground(new java.awt.Color(85, 90, 96));
        btn_5.setText("5");
        btn_5.setBorder(null);
        btn_5.setContentAreaFilled(false);
        btn_5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_5.setFocusPainted(false);
        btn_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_5.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_5.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_02.png"))); // NOI18N
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setBackground(new java.awt.Color(204, 204, 204));
        btn_6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_6.setForeground(new java.awt.Color(85, 90, 96));
        btn_6.setText("6");
        btn_6.setBorder(null);
        btn_6.setContentAreaFilled(false);
        btn_6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_6.setFocusPainted(false);
        btn_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_6.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_6.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_02.png"))); // NOI18N
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_1.setBackground(new java.awt.Color(204, 204, 204));
        btn_1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_1.setForeground(new java.awt.Color(85, 90, 96));
        btn_1.setText("1");
        btn_1.setBorder(null);
        btn_1.setContentAreaFilled(false);
        btn_1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_1.setFocusPainted(false);
        btn_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_1.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_1.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_02.png"))); // NOI18N
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(204, 204, 204));
        btn_2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_2.setForeground(new java.awt.Color(85, 90, 96));
        btn_2.setText("2");
        btn_2.setBorder(null);
        btn_2.setContentAreaFilled(false);
        btn_2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_2.setFocusPainted(false);
        btn_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_2.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_2.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_02.png"))); // NOI18N
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setBackground(new java.awt.Color(204, 204, 204));
        btn_3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_3.setForeground(new java.awt.Color(85, 90, 96));
        btn_3.setText("3");
        btn_3.setBorder(null);
        btn_3.setContentAreaFilled(false);
        btn_3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_3.setFocusPainted(false);
        btn_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_3.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_3.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_02.png"))); // NOI18N
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_punto.setBackground(new java.awt.Color(204, 204, 204));
        btn_punto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_punto.setForeground(new java.awt.Color(85, 90, 96));
        btn_punto.setText(".");
        btn_punto.setBorder(null);
        btn_punto.setContentAreaFilled(false);
        btn_punto.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_punto.setFocusPainted(false);
        btn_punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_punto.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_punto.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_punto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_02.png"))); // NOI18N
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_0.setBackground(new java.awt.Color(204, 204, 204));
        btn_0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_0.setForeground(new java.awt.Color(85, 90, 96));
        btn_0.setText("0");
        btn_0.setBorder(null);
        btn_0.setContentAreaFilled(false);
        btn_0.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_0.setFocusPainted(false);
        btn_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_0.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_0.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_02.png"))); // NOI18N
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_00.setBackground(new java.awt.Color(204, 204, 204));
        btn_00.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_00.setForeground(new java.awt.Color(85, 90, 96));
        btn_00.setText("00");
        btn_00.setBorder(null);
        btn_00.setContentAreaFilled(false);
        btn_00.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_00.setFocusPainted(false);
        btn_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_00.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_00.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_00.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_02.png"))); // NOI18N
        btn_00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_00ActionPerformed(evt);
            }
        });

        btn_multi.setBackground(new java.awt.Color(204, 204, 204));
        btn_multi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_multi.setForeground(new java.awt.Color(42, 123, 179));
        btn_multi.setText("*");
        btn_multi.setBorder(null);
        btn_multi.setContentAreaFilled(false);
        btn_multi.setFocusPainted(false);
        btn_multi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_multi.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_multi.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_multi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiActionPerformed(evt);
            }
        });

        btn_menos.setBackground(new java.awt.Color(204, 204, 204));
        btn_menos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_menos.setForeground(new java.awt.Color(42, 123, 179));
        btn_menos.setText("-");
        btn_menos.setBorder(null);
        btn_menos.setContentAreaFilled(false);
        btn_menos.setFocusPainted(false);
        btn_menos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_menos.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_menos.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_menos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });

        btn_igual.setBackground(new java.awt.Color(204, 204, 204));
        btn_igual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_igual.setForeground(new java.awt.Color(42, 123, 179));
        btn_igual.setText("=");
        btn_igual.setBorder(null);
        btn_igual.setContentAreaFilled(false);
        btn_igual.setFocusPainted(false);
        btn_igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_igual.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_igual.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_igual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        btn_mas.setBackground(new java.awt.Color(204, 204, 204));
        btn_mas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_mas.setForeground(new java.awt.Color(42, 123, 179));
        btn_mas.setText("+");
        btn_mas.setBorder(null);
        btn_mas.setContentAreaFilled(false);
        btn_mas.setFocusPainted(false);
        btn_mas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mas.setMaximumSize(new java.awt.Dimension(300, 300));
        btn_mas.setPreferredSize(new java.awt.Dimension(300, 300));
        btn_mas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_01.png"))); // NOI18N
        btn_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout botoneraLayout = new javax.swing.GroupLayout(botonera);
        botonera.setLayout(botoneraLayout);
        botoneraLayout.setHorizontalGroup(
            botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoneraLayout.createSequentialGroup()
                .addGroup(botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(botoneraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, botoneraLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(botoneraLayout.createSequentialGroup()
                                .addComponent(btn_c, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_porc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(botoneraLayout.createSequentialGroup()
                                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(botoneraLayout.createSequentialGroup()
                                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(botoneraLayout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(botoneraLayout.createSequentialGroup()
                                .addComponent(btn_00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        botoneraLayout.setVerticalGroup(
            botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoneraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_porc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_c, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(botonera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 280, 350));

        pantalla.setBackground(new java.awt.Color(236, 250, 253));
        pantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_modo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_modo2.png"))); // NOI18N
        btn_modo.setBorder(null);
        btn_modo.setBorderPainted(false);
        btn_modo.setContentAreaFilled(false);
        btn_modo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_modo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modoActionPerformed(evt);
            }
        });
        pantalla.add(btn_modo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 50, 20));

        txtoperacion.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtoperacion.setForeground(new java.awt.Color(42, 123, 179));
        txtoperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.add(txtoperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 240, 44));

        txtresultado.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        txtresultado.setForeground(new java.awt.Color(42, 123, 179));
        txtresultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtresultado.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtresultadoComponentAdded(evt);
            }
        });
        pantalla.add(txtresultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 240, 50));

        jPanel1.add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 280, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minumMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minumMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void decoradeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decoradeMouseDragged

        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_decoradeMouseDragged

    private void decoradeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decoradeMousePressed

        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_decoradeMousePressed

    private void minum1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minum1MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minum1MouseClicked

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        this.dispose();
    }//GEN-LAST:event_exit1MouseClicked

    private void decorade1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decorade1MouseDragged

        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_decorade1MouseDragged

    private void decorade1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decorade1MousePressed

        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_decorade1MousePressed

    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        txtoperacion.setText("");
        txtresultado.setText("");
    }//GEN-LAST:event_btn_cActionPerformed

    private void btn_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ceActionPerformed
        String texto = txtoperacion.getText().substring(0, txtoperacion.getText().length() - 1);
        txtoperacion.setText(texto);
    }//GEN-LAST:event_btn_ceActionPerformed

    private void btn_porcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_porcActionPerformed
        addNumber("%");
    }//GEN-LAST:event_btn_porcActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
        addNumber("/");
    }//GEN-LAST:event_btn_divActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        addNumber("7");
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        addNumber("8");
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        addNumber("9");
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        addNumber("4");
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        addNumber("5");
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        addNumber("6");
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        addNumber("1");
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        addNumber("2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        addNumber("3");
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        addNumber(".");
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        addNumber("0");
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_00ActionPerformed
        addNumber("00");
    }//GEN-LAST:event_btn_00ActionPerformed

    private void btn_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiActionPerformed
        addNumber("*");
    }//GEN-LAST:event_btn_multiActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed
        addNumber("-");
    }//GEN-LAST:event_btn_menosActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed

        try {

            //            String resultado = se.eval(txtoperacion.getText()).toString();
            //            txtresultado.setText(resultado);
            char cc;
            String operacion = txtoperacion.getText();

            int ei, esw;
            float ep, es;

            ei = 0;
            esw = 0;

            do {
                cc = operacion.charAt(ei);
                if (cc == '/') {
                    ep = Float.parseFloat(operacion.substring(0, ei));

                    es = Float.parseFloat(operacion.substring(ei + 1));

                    float resultado = (ep / es);
                    String Result = String.valueOf(resultado);
                    txtresultado.setText(Result);

                    esw = 1;
                } else {
                    if (cc == '*') {
                        ep = Float.parseFloat(operacion.substring(0, ei));

                        es = Float.parseFloat(operacion.substring(ei + 1));

                        float resultado = (ep * es);
                        String Result = String.valueOf(resultado);
                        txtresultado.setText(Result);

                        esw = 1;
                    } else {
                        if (cc == '+') {
                            ep = Float.parseFloat(operacion.substring(0, ei));

                            es = Float.parseFloat(operacion.substring(ei + 1));

                            float resultado = (ep + es);

                            //                        System.out.println("Resultado:  " + resultado);
                            String Result = String.valueOf(resultado);
                            txtresultado.setText(Result);

                            esw = 1;
                        } else {
                            if (cc == '-') {
                                ep = Float.parseFloat(operacion.substring(0, ei));

                                es = Float.parseFloat(operacion.substring(ei + 1));

                                float resultado = (ep - es);
                                String Result = String.valueOf(resultado);
                                txtresultado.setText(Result);

                                esw = 1;
                            } else {
                                ei++;
                            }
                        }

                    }
                }
            } while ((ei < operacion.length() - 1) && (esw == 0));

        } catch (Exception e) {
            txtresultado.setText("Error");

        }
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masActionPerformed
        addNumber("+");
    }//GEN-LAST:event_btn_masActionPerformed

    boolean modo_oscuro = false;
    
    private void btn_modoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modoActionPerformed

        if (!modo_oscuro) {

            //cambia de color los paneles
            btn_modo.setIcon(new ImageIcon(getClass().getResource("/imagenes/btn_modo1.png")));
            pantalla.setBackground(Color.decode("#52646e"));
            botonera.setBackground(Color.decode("#52646e"));

            //cambia de color la fuente de las cajas de texto
            txtoperacion.setForeground(Color.decode("#fbffff"));
            txtresultado.setForeground(Color.decode("#fbffff"));

            //cambia los iconos de los botones a modo oscuro
            //setIcon - asignar icono base
            btn_igual.setIcon(new ImageIcon(getClass().getResource("/imagenes/btn_2_dark.png")));
            btn_mas.setIcon(new ImageIcon(getClass().getResource("/imagenes/btn_2_dark.png")));
            btn_menos.setIcon(new ImageIcon(getClass().getResource("/imagenes/btn_2_dark.png")));
            btn_multi.setIcon(new ImageIcon(getClass().getResource("/imagenes/btn_2_dark.png")));
            btn_div.setIcon(new ImageIcon(getClass().getResource("/imagenes/btn_2_dark.png")));

            //setRolloverIcon - icono sobre cursor
            btn_1.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_2.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_3.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_4.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_5.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_6.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_7.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_8.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_9.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_0.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_00.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_punto.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));

            // boton presionado//
            btn_c.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));

            btn_c.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_3_dark.png")));
            btn_div.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_3_dark.png")));
            btn_multi.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_3_dark.png")));
            btn_menos.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_3_dark.png")));
            btn_mas.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_3_dark.png")));
            btn_igual.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_3_dark.png")));

            btn_punto.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_0.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_00.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_1.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_2.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_3.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_4.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_5.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_6.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_7.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_8.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_9.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_ce.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_porc.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));

            //cambia de color la fuente de los btn
            btn_1.setForeground(Color.decode("#fbffff"));
            btn_2.setForeground(Color.decode("#fbffff"));
            btn_3.setForeground(Color.decode("#fbffff"));
            btn_4.setForeground(Color.decode("#fbffff"));
            btn_5.setForeground(Color.decode("#fbffff"));
            btn_6.setForeground(Color.decode("#fbffff"));
            btn_7.setForeground(Color.decode("#fbffff"));
            btn_8.setForeground(Color.decode("#fbffff"));
            btn_9.setForeground(Color.decode("#fbffff"));
            btn_0.setForeground(Color.decode("#fbffff"));
            btn_00.setForeground(Color.decode("#fbffff"));
            btn_porc.setForeground(Color.decode("#fbffff"));
            btn_ce.setForeground(Color.decode("#fbffff"));
            btn_punto.setForeground(Color.decode("#fbffff"));
            btn_igual.setForeground(Color.decode("#fbffff"));
            btn_mas.setForeground(Color.decode("#fbffff"));
            btn_menos.setForeground(Color.decode("#fbffff"));
            btn_multi.setForeground(Color.decode("#fbffff"));
            btn_div.setForeground(Color.decode("#fbffff"));
            btn_c.setForeground(Color.decode("#41a3ca"));

            modo_oscuro = true;
        } else {
                   if (!modo_oscuro) {

            //cambia de color los paneles
            btn_modo.setIcon(new ImageIcon(getClass().getResource("/imagenes/btn_modo1.png")));
            pantalla.setBackground(Color.decode("#52646e"));
            botonera.setBackground(Color.decode("#52646e"));

            //cambia de color la fuente de las cajas de texto
            txtoperacion.setForeground(Color.decode("#fbffff"));
            txtresultado.setForeground(Color.decode("#fbffff"));

            //cambia los iconos de los botones a modo oscuro
            //setIcon - asignar icono base
            btn_igual.setIcon(new ImageIcon(getClass().getResource("/imagenes/btn_2_dark.png")));
            btn_mas.setIcon(new ImageIcon(getClass().getResource("/imagenes/btn_2_dark.png")));
            btn_menos.setIcon(new ImageIcon(getClass().getResource("/imagenes/btn_2_dark.png")));
            btn_multi.setIcon(new ImageIcon(getClass().getResource("/imagenes/btn_2_dark.png")));
            btn_div.setIcon(new ImageIcon(getClass().getResource("/imagenes/btn_2_dark.png")));

            //setRolloverIcon - icono sobre cursor
            btn_1.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_2.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_3.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_4.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_5.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_6.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_7.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_8.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_9.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_0.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_00.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));
            btn_punto.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));

            // boton presionado//
            btn_c.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_1_dark.png")));

            btn_c.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_3_dark.png")));
            btn_div.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_3_dark.png")));
            btn_multi.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_3_dark.png")));
            btn_menos.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_3_dark.png")));
            btn_mas.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_3_dark.png")));
            btn_igual.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_3_dark.png")));

            btn_punto.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_0.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_00.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_1.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_2.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_3.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_4.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_5.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_6.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_7.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_8.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_9.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_ce.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));
            btn_porc.setPressedIcon(new ImageIcon(getClass().getResource("/imagenes/btn_5_dark.png")));

            //cambia de color la fuente de los btn
            btn_1.setForeground(Color.decode("#fbffff"));
            btn_2.setForeground(Color.decode("#fbffff"));
            btn_3.setForeground(Color.decode("#fbffff"));
            btn_4.setForeground(Color.decode("#fbffff"));
            btn_5.setForeground(Color.decode("#fbffff"));
            btn_6.setForeground(Color.decode("#fbffff"));
            btn_7.setForeground(Color.decode("#fbffff"));
            btn_8.setForeground(Color.decode("#fbffff"));
            btn_9.setForeground(Color.decode("#fbffff"));
            btn_0.setForeground(Color.decode("#fbffff"));
            btn_00.setForeground(Color.decode("#fbffff"));
            btn_porc.setForeground(Color.decode("#fbffff"));
            btn_ce.setForeground(Color.decode("#fbffff"));
            btn_punto.setForeground(Color.decode("#fbffff"));
            btn_igual.setForeground(Color.decode("#fbffff"));
            btn_mas.setForeground(Color.decode("#fbffff"));
            btn_menos.setForeground(Color.decode("#fbffff"));
            btn_multi.setForeground(Color.decode("#fbffff"));
            btn_div.setForeground(Color.decode("#fbffff"));
            btn_c.setForeground(Color.decode("#41a3ca"));

            modo_oscuro = true;
        } else {
            Panel frame = new Panel();
            this.dispose();
            frame.setVisible(true);
        }
        }
    }//GEN-LAST:event_btn_modoActionPerformed

    private void txtresultadoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtresultadoComponentAdded
        
    }//GEN-LAST:event_txtresultadoComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora_facherita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora_facherita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora_facherita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora_facherita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora_facherita().setVisible(true);
            }
        });
    }
    public void addNumber(String digito){
        txtoperacion.setText(txtoperacion.getText()+digito);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonera;
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_00;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_ce;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_mas;
    private javax.swing.JButton btn_menos;
    private javax.swing.JButton btn_modo;
    private javax.swing.JButton btn_multi;
    private javax.swing.JButton btn_porc;
    private javax.swing.JButton btn_punto;
    private javax.swing.JPanel decorade;
    private javax.swing.JPanel decorade1;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel minum;
    private javax.swing.JLabel minum1;
    private javax.swing.JPanel pantalla;
    private javax.swing.JLabel txtoperacion;
    private javax.swing.JLabel txtresultado;
    // End of variables declaration//GEN-END:variables

}